---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Example assertion
      ansible.builtin.command: sqlplus -V
      register: result
      changed_when: false

    - name: Show version
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines[2] }}"
