name: "jmsierra.oracle.instantclient"
on:
  push:
    paths:
      - 'roles/instantclient/**'
      - 'molecule/instantclient/**'
      - '.github/workflows/instantclient.yml'
      - 'molecule/common/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'roles/instantclient/**'
      - 'molecule/instantclient/**'
      - '.github/workflows/instantclient.yml'
      - 'molecule/common/**'
      - 'requirements.txt'

defaults:
  run:
    working-directory: 'jmsierra.oracle.instantclient'

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        distro:
          - centos7
          - centos8
          - debian10
          - ubuntu2004
        collection_role:
          - instantclient
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: 'jmsierra.oracle.instantclient'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies.
        run: pip3 install -r requirements.txt

      - name: Install the collection
        run: ansible-galaxy collection install . --force

      - name: Run role tests
        run: molecule test -s ${{ matrix.collection_role }}
        working-directory: jmsierra.oracle.instantclient/extensions
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
