---
dependencies: []

galaxy_info:
  role_name: jmsierra.oracle.instantclient
  description: Oracle InstantClient+SQLPLUS for Linux
  min_ansible_version: 2.10
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - oracle
    - client
    - instantclient
    - sqlplus
